spring:
  datasource:
    username: beer_service    password: password
    url: jdbc:mysql://192.168.99.101:3306/beerservice?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC  jpa:    database: mysql
    hibernate:      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect