server:
  port: 9090
# setting logging level to debug
logging:
  level:
    guru: debug
spring:
  application:    name: beer-service
# defaults for docker image - vromero/activemq-artemis
  artemis:
    host: 192.168.99.101
    user: artemis
    password: simetraehcapa  datasource:
    initialization-mode: embedded
    url: jdbc:h2:mem:testdb;MODE=MYSQL
  cache:    jcache:      config: classpath:ehcache.xml  h2:    console:      enabled: true  zipkin:    base-url: http://192.168.99.101:9411sfg: 
  brewery: 
    beer-inventory-service-host: http://localhost:9092