server:
  port: 9090
spring:
# defaults for docker image - vromero/activemq-artemis
  artemis:
    host: 192.168.99.101
    user: artemis
    password: simetraehcapa  datasource:
    initialization-mode: embedded
    url: jdbc:h2:mem:testdb;MODE=MYSQL
  cache:    jcache:      config: classpath:ehcache.xml  h2:    console:      enabled: truesfg: 
  brewery: 
    beer-inventory-service-host: http://localhost:9092